language: ruby
rvm:
- 2.6.3
services:
- postgresql
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: DOvqc4baRiR8tWKQJNM4c6qgXGWXihrLhL3zqOb92STG2b/yIwwP8U2/lVIJRgjF/C2LeakuerRxVlXI+QNmZLGIdKVPs+RKj2qZ/6dUhdLnGNdzYcYsz9zBKnGCkyv4hBpQU5UL3cZokiFXtSL1YGCZY8a1drjA0vYdZFDp4Ur9lsXzC7e/ahGwpNu1MFrTQ2rTSendwHYyDywizrE+Z2VarKLwZ3lMhRJv0+kVMS4LoxnHxnOBPLPDQLkRWLcxjHTQd6OFih51TAAFNu3L4JMuNmxzJwAGIaaqlPFsy9CTjbIMUvdVL9stQyfW256qOga8II75bVRVpHkZOIhh1J/lRLfRXimCUyyRQJIQ7fbAF3FraT5SddCYoOLsQ1StS5W4PIff+VlnMccZQIL4mmEmDDRf+9TTrGY0MtDxwgFjItYyUickNDSo9UW911eTRMgg/xsQmJ770fbo2LHWdmQlBRG0wELaRpMPDKH09SfsQxbg/ZPDJEPMR3N4yFqJMfyCknJDLmXv4Va6nVmt6Q5QCRyrhqvXURAPCPWkPwGLA5an17l2Tmp89I/Fe5wtpdo4sV3HGUi3p0vfH7qQ5VauiZ6bA5iZhjmzNuxPo5NNzIuPdiKkYfNKH0Ctq8CqeBb4SeMwsNVNW/yeChYlRM2Zm0oZ7WucfKDcpMkoN/4=
  app: expense-tracker-sinatra
  on:
    repo: AndreaDiotallevi/expense-tracker
